site_name: The Eternal King
site_url: https://blackbat13.github.io/eternal-king/
plugins:
  - search
  - privacy
copyright: >
  Copyright &copy; 2025 - 2025 Damian Kurpiewski
theme:
  name: material
  language: pl
  icon:
    logo: material/castle
  font:
    text: Amarante
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Dark mode
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - toc.follow
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - tables
extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
nav:
  - 'Universe of the Eternal King': 'index.md'
  - 'Characters':
    - 'Damien - The Eternal King': 'characters/damien.md'
    - 'Xeroth': 'characters/xeroth.md'
    - 'Lorain': 'characters/lorain.md'
    - 'Vera': 'characters/vera.md'
    - 'Agnes': 'characters/agnes.md'
    - 'Nyx': 'characters/nyx.md'
  - 'Stories':
    - 'Lorain':
      - 'Sweet Sixteen': 'stories/lorain/001.md'
      - '18th Birthday': 'stories/lorain/002.md'
      - 'Study Break': 'stories/lorain/003.md'
      - 'The Barista Experience': 'stories/lorain/004.md'
      - 'MIT': 'stories/lorain/005.md'
      - 'Retirement': 'stories/lorain/006.md'
      - 'Enough with the Witches': 'stories/lorain/007.md'
      - 'The Past': 'stories/lorain/008.md'
      - 'Fatherly Love': 'stories/lorain/009.md'
      - 'Eternal Damnation': 'stories/lorain/010.md'
      - 'Too Soon?': 'stories/lorain/011.md'
      - 'Costly Mistake': 'stories/lorain/012.md'
      - 'First Universe': 'stories/lorain/013.md'
      - 'Till Death Do Us Part': 'stories/lorain/014.md'
      - 'Matchmaking': 'stories/lorain/015.md'
      - 'Shopping Spree': 'stories/lorain/016.md'
      - 'The Many Deaths of Lorain': 'stories/lorain/017.md'
      - 'Shape-shifting for Dummies': 'stories/lorain/018.md'
    - 'Various Stories':
      - 'Stubborn Cult': 'stories/misc/stubborn_cult.md'
      - 'Roll the Dice': 'stories/misc/roll_the_dice.md'
      - '(Un)deadly Conundrum': 'stories/misc/undeadly_conundrum.md'