site_name: ETERNAL-KING
site_url: https://blackbat13.github.io/eternal-king/
plugins:
  - search
  - privacy
copyright: >
  Copyright &copy; 2025 - 2025 Damian Kurpiewski
theme:
  name: material
  language: pl
  icon:
    logo: material/castle
  font:
    text: Metamorphous
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Dark mode
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - toc.follow
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - tables
extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - 'Universe of the Eternal King': 'index.md'